import React, { useState } from 'react';
import { Bot, LoaderCircle, Send, ShieldCheck } from 'lucide-react';
import { api } from '../services/api';

export default function AIAssistant(){
  const [messages,setMessages]=useState([{role:'bot',text:'Hello. I can help explain the verification workflow, document checklist and application status. What would you like to know?'}]);
  const [question,setQuestion]=useState('');
  const [busy,setBusy]=useState(false);
  async function ask(value=question){const text=value.trim();if(!text||busy)return;setQuestion('');setMessages(current=>[...current,{role:'user',text}]);setBusy(true);try{const {data}=await api.post('/ai/assistant',{question:text});setMessages(current=>[...current,{role:'bot',text:data.answer}]);}catch(error){setMessages(current=>[...current,{role:'bot',text:error.response?.data?.message||'I could not reach the advisory service. Please contact the concerned Legal Metrology authority.'}]);}finally{setBusy(false);}}
  return <div className="assistant-layout"><div className="panel assistant-chat"><div className="assistant-head"><div className="bot-avatar"><Bot size={20}/></div><div><strong>Metrology AI Assistant</strong><small>Advisory guidance · source-grounded</small></div><span className="online"><i></i> Online</span></div><div className="chat-body">{messages.map((message,index)=><div className={`chat-msg ${message.role}`} key={`${message.role}-${index}`}>{message.text}</div>)}<div className="quick-questions"><button onClick={()=>ask('What documents are required?')}>What documents do I need?</button><button onClick={()=>ask('How do I renew a certificate?')}>How do I renew?</button><button onClick={()=>ask('How can I find a GATC test centre?')}>Find a test centre</button></div>{busy&&<div className="ai-typing"><LoaderCircle className="spin" size={14}/> Checking approved guidance...</div>}</div><div className="chat-input"><input value={question} onChange={event=>setQuestion(event.target.value)} onKeyDown={event=>event.key==='Enter'&&ask()} placeholder="Ask about the process..."/><button className="btn btn-primary" onClick={()=>ask()} disabled={busy}><Send size={15}/> Send</button></div></div><div className="panel guide-card"><div className="eyebrow">ADVISORY ONLY</div><h2>Answers grounded in approved guidance.</h2><p>This assistant does not invent laws, fees or deadlines. Final certification decisions remain with the authorized authority.</p><div className="guide-question"><ShieldCheck size={17}/><strong>When uncertain, it directs you to the concerned Legal Metrology authority.</strong></div></div></div>;
}