import React, { useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, FileUp, LoaderCircle, Save, Send, ShieldCheck, UploadCloud } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';

function ErrorMessage({ message }) { return message ? <div className="form-error"><AlertCircle size={16}/>{message}</div> : null; }
export function Login() { const { login, register } = useAuth(); const navigate=useNavigate(); const [mode,setMode]=useState('login'); const [form,setForm]=useState({name:'',email:'business@smartmetrix.demo',password:'Demo@12345',role:'BUSINESS'}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  async function submit(event){event.preventDefault();setBusy(true);setError('');try{const authenticatedUser=await (mode==='login'?login(form.email,form.password):register(form));navigate(authenticatedUser.role==='LMO'?'/lmo/dashboard':authenticatedUser.role==='GATC'?'/gatc/dashboard':authenticatedUser.role==='HEAD_OFFICER'?'/head/dashboard':authenticatedUser.role==='ADMIN'?'/admin/dashboard':'/business/dashboard');}catch(e){setError(e.response?.data?.message||'Unable to connect to the Legal Metrology Digital System API.');}finally{setBusy(false);}}
    /* accidental duplicate removed */
  return <main className="auth-page"><div className="auth-panel"><div className="auth-brand"><div className="brand-mark"><ShieldCheck size={19}/></div><strong>Smart<span>Metrix</span></strong></div><div className="eyebrow">SECURE WORKSPACE</div><h1>{mode==='login'?'Welcome back.':'Create a workspace.'}</h1><p>{mode==='login'?'Sign in to continue your instrument verification workflow.':'Register a demo account to explore the connected workflow.'}</p><form onSubmit={submit}>{mode==='register'&&<label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{mode==='register'&&<label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="BUSINESS">Business</option><option value="LMO">Legal Metrology Officer</option><option value="GATC">Approved Test Centre</option></select></label>}<ErrorMessage message={error}/><button className="btn btn-primary full" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:<Send size={16}/>} {mode==='login'?'Sign in':'Create account'}</button></form><button className="auth-switch" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Need a new demo account? Register':'Already have an account? Sign in'}</button><small className="auth-note">DEMO DATA - NOT GOVERNMENT RECORDS</small></div><div className="auth-aside"><span className="eyebrow">OFFICER-LED VERIFICATION</span><h2>One chain of custody for every instrument.</h2><p>Applications, inspections, reports and prototype records stay connected, auditable and ready for authorized review.</p><div className="auth-check"><CheckCircle2 size={16}/> AI assistance remains advisory</div><div className="auth-check"><CheckCircle2 size={16}/> Decisions remain with the competent authority</div></div></main> }

export function RegisterInstrument(){ const navigate=useNavigate(); const [form,setForm]=useState({type:'Digital Weighing Machine',category:'Weighing instrument',manufacturer:'',modelNumber:'',serialNumber:'',capacity:'',accuracyClass:'III',installationLocation:''}); const [files,setFiles]=useState([]); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  function update(key,value){setForm({...form,[key]:value})} async function submit(event){event.preventDefault();setBusy(true);setError('');try{const body=new FormData();Object.entries(form).forEach(([key,value])=>body.append(key,value));files.forEach(file=>body.append('documents',file));const {data:instrument}=await api.post('/instruments',body);await api.post('/applications',{instrument:instrument._id});navigate('/business/applications');}catch(e){setError(e.response?.data?.message||'Could not submit the application.');}finally{setBusy(false);}}
  return <main className="content"><div className="page-heading"><div><div className="eyebrow">BUSINESS WORKFLOW <span>•</span> STEP 1 OF 3</div><h1>Register an instrument</h1><p>Add the instrument that needs verification. You can attach evidence before submitting.</p></div></div><form className="workflow-form" onSubmit={submit}><div className="panel form-section"><div className="form-section-title"><div><h2>Instrument details</h2><p>Use the exact information shown on the manufacturer's plate.</p></div><span>Required fields marked *</span></div><div className="form-grid"><label>Instrument type *<select value={form.type} onChange={e=>update('type',e.target.value)}><option>Digital Weighing Machine</option><option>Platform Scale</option><option>Counter Scale</option><option>Weighbridge</option><option>Measuring instrument</option></select></label><label>Category *<input required value={form.category} onChange={e=>update('category',e.target.value)}/></label><label>Manufacturer *<input required value={form.manufacturer} onChange={e=>update('manufacturer',e.target.value)}/></label><label>Model number<input value={form.modelNumber} onChange={e=>update('modelNumber',e.target.value)}/></label><label>Serial number *<input required value={form.serialNumber} onChange={e=>update('serialNumber',e.target.value)}/></label><label>Capacity<input value={form.capacity} onChange={e=>update('capacity',e.target.value)} placeholder="e.g. 150 kg"/></label><label>Accuracy class<input value={form.accuracyClass} onChange={e=>update('accuracyClass',e.target.value)}/></label><label>Installation location *<input required value={form.installationLocation} onChange={e=>update('installationLocation',e.target.value)} placeholder="City, state"/></label></div></div><div className="panel form-section"><div className="form-section-title"><div><h2>Supporting documents</h2><p>JPG, PNG or PDF files up to 5 MB each. AI pre-checks are advisory.</p></div><FileUp size={20}/></div><label className="upload-zone"><input type="file" multiple accept="image/jpeg,image/png,application/pdf" onChange={e=>setFiles(Array.from(e.target.files||[]))}/><UploadCloud size={24}/><strong>Drop evidence here or browse</strong><small>Instrument photo, serial plate, previous certificate</small></label>{files.length>0&&<div className="file-list">{files.map(file=><span key={file.name}><FileUp size={14}/>{file.name}</span>)}</div>}</div><ErrorMessage message={error}/><div className="form-actions"><button type="button" className="btn btn-secondary" onClick={()=>navigate('/business/instruments')}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?<LoaderCircle className="spin" size={16}/>:<Save size={16}/>} Save instrument</button></div></form></main> }

export function ApplicationsLive({ role='Business' }){ const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [selected,setSelected]=useState(null); const [remarks,setRemarks]=useState(''); const [busy,setBusy]=useState(false); const location=useLocation();
  async function load(){try{const {data}=await api.get('/applications');setItems(data)}catch(e){setError(e.response?.data?.message||'Could not load applications.')}finally{setLoading(false)}} useEffect(()=>{load()},[]);
  async function status(status){setBusy(true);try{await api.patch(`/applications/${selected._id}/status`,{status,remarks});setSelected(null);setRemarks('');load()}catch(e){setError(e.response?.data?.message||'Could not update the application.')}finally{setBusy(false)}}
  return <div className="panel table-panel live-applications"><div className="panel-title"><div><h2>{role==='LMO'?'Review queue':'Your applications'}</h2><p className="panel-subtitle">Live records from MongoDB · {items.length} found</p></div><button onClick={load}>Refresh</button></div>{error&&<ErrorMessage message={error}/>} {loading?<div className="empty-state"><LoaderCircle className="spin"/>Loading records...</div>:items.length===0?<div className="empty-state">No applications yet. Register an instrument to start.</div>:<div className="table-scroll"><table><thead><tr><th>Instrument</th><th>Serial number</th><th>Status</th><th>Submitted</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item._id}><td><strong>{item.instrument?.type||'Instrument'}</strong><small>{item.instrument?.manufacturer||'Business record'}</small></td><td>{item.instrument?.serialNumber}</td><td><span className="status"><i></i>{item.status}</span></td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td><button className="text-btn" onClick={()=>setSelected(item)}>Review <Send size={13}/></button></td></tr>)}</tbody></table></div>}{selected&&<div className="review-drawer"><div className="drawer-head"><div><div className="eyebrow">{selected.status}</div><h2>{selected.instrument?.type}</h2></div><button onClick={()=>setSelected(null)}>×</button></div><div className="review-summary"><span>Serial number<strong>{selected.instrument?.serialNumber}</strong></span><span>Capacity<strong>{selected.instrument?.capacity||'Not provided'}</strong></span><span>Location<strong>{selected.instrument?.installationLocation}</strong></span></div><label>Officer remarks<textarea value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="Add a transparent review note..."/></label><div className="form-actions"><button className="btn btn-secondary" disabled={busy} onClick={()=>status('RETURNED')}>Return for correction</button><button className="btn btn-primary" disabled={busy} onClick={()=>status(role==='LMO'?'APPROVED':'OFFICER_REVIEW')}>{role==='LMO'?'Approve application':'Send to officer'}</button></div></div>}</div> }
